import pyqiwi
import time
import os

wallet = pyqiwi.Wallet(token='сюда токен', number='79999999999') # Авторизация кошелька с корого будут переводы.
os.system('cls')
print('Баланс на данный момент составляет ', wallet.balance(), ' рублей.')
time.sleep(2)
print('Начинаем переводить деньги на кошельки')
wallet.send('99', recipient='79999999999', amount=1, comment='раз')
print('№1 платёж ушёл')
print('Баланс на данный момент составляет ', wallet.balance(), ' рублей.')
time.sleep(2)
wallet.send('99', recipient='79999999999', amount=1, comment='два')
print('№2 платёж ушёл')
print('Баланс на данный момент составляет ', wallet.balance(), ' рублей.')
time.sleep(2)
wallet.send('99', recipient='79999999999', amount=1, comment='три')
print('№3 платёж ушёл')
print('Баланс на данный момент составляет ', wallet.balance(), ' рублей.')
time.sleep(2)
wallet.send('99', recipient='79999999999', amount=1, comment='четыре')
print('№4 платёж ушёл')
print('Баланс на данный момент составляет ', wallet.balance(), ' рублей.')
time.sleep(2)
wallet.send('99', recipient='79999999999', amount=1, comment='пять')
print('№5 платёж ушёл')
print('Баланс на данный момент составляет ', wallet.balance(), ' рублей.')
time.sleep(2)
wallet.send('99', recipient='79999999999', amount=1, comment='шесть')
print('№6 платёж ушёл')
print('Баланс на данный момент составляет ', wallet.balance(), ' рублей.')
time.sleep(2)
wallet.send('99', recipient='79999999999', amount=1, comment='семь')
print('№7 платёж ушёл')
print('Баланс на данный момент составляет ', wallet.balance(), ' рублей.')
time.sleep(2)
wallet.send('99', recipient='79999999999', amount=1, comment='восемь')
print('№8 платёж ушёл')
print('Все платежи выполнены.')
